### ISSUE TITLE
Error CS0246 in Unity 5.3.6f1

### ISSUE THREAD

**Issue by aiioodof** [handcircus/Unity-Resource-Checker#19]
Assets/Editor/ResourceChecker.cs(376,65): error CS0246: The type or namespace name `Texture2DArray' could not be found. Are you missing a using directive or an assembly reference?
Assets/Editor/ResourceChecker.cs(395,67): error CS0246: The type or namespace name `Texture2DArray' could not be found. Are you missing a using directive or an assembly reference?
Assets/Editor/ResourceChecker.cs(396,56): error CS0246: The type or namespace name `Texture2DArray' could not be found. Are you missing a using directive or an assembly reference?
Assets/Editor/ResourceChecker.cs(1027,40): error CS0246: The type or namespace name `Texture2DArray' could not be found. Are you missing a using directive or an assembly reference?
Assets/Editor/ResourceChecker.cs(1028,56): error CS0246: The type or namespace name `Texture2DArray' could not be found. Are you missing a using directive or an assembly reference?

**Comment by handcircus** [comment]
This should be fine on 5.4 and 5.5 (when Texture2DArray was introduced). You should be able to comment this out if you are still on 5.3.
